#!/bin/bash

set -xe

sed "s/APPNAME/$CF_APP/" ./git-assets/ci/manifest.yml > ./app-manifest-output/manifest-tmp.yml
sed "s/APPPATH/..\/pre-release\/$CF_APP-$(cat ./version/number).jar/" ./app-manifest-output/manifest-tmp.yml > ./app-manifest-output/manifest.yml

cat ./app-manifest-output/manifest.yml
